# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Elsa in Wonderland
email: zhangqing0627@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
   Master student in SJTU, dream to be a PM!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: /vacant
github_username:  smilevera
header-img:img/home-bg.jpg

# Build settings

highlighter: rouge
permalink: pretty
paginate: 10

anchorjs: true 
exclude:
  - Gemfile
  - Gemfile.lock
